namespace PhazeX.Network
{
    public enum pxMessages : byte
    {
        Chat = 0,
        Login = 1,
        Status = 2,
        LogOff = 3,
        Hand = 4,
        HandRequest = 5,
        Goodbye = 6,
        GameStarting = 7,
        StartGame = 8,
        GetTopDeckCard = 9,
        GetTopDiscard = 10,
        GotCards = 11,
        Discard = 12,
        Ready = 13,
        TurnStart = 14,
        TurnEnd = 15,
        GetCurrentPhaze = 16,
        CurrentPhaze = 17,
        GetPlayerInfo = 18,
        PlayerInfo = 19,
        Meld = 20,
        PlayOnGroup = 21,
        ReadTable = 22,
        Table = 23,
        //unused (24, 25)
        GetGameRules = 26,
        GameRules = 27,
        UpdateDiscard = 28,
        LoginAcknowledgment = 29,
        Scoreboard = 30,
        RequestHand = 31,
        NewHand = 32,
        DiscardSkip = 33,
        ChangeName = 34,
        ChangeNameReject = 35,
        GotDeckCard = 36,
        GotDiscard = 37,
        WentOut = 38,
        Won = 39,
        PlayedCardOnTable = 40,
        GameOver = 41,
        CompletedPhaze = 42,
        SkipNotification = 43,
        StartGameTimer = 44,
        RequestTable = 45,
        Heartbeat = 170,
        DialogMessage = 252,
        ErrorMessage = 253,
        SystemMessage = 254
    }
}
